# Generated by Django 2.2.5 on 2019-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190912_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.CharField(max_length=20000),
        ),
    ]
